### ISSUE TITLE
key_query error

### ISSUE THREAD

**Issue by Valinwolf** [matrix-construct/construct#99] opened 2019-08-01 01:50 UTC
Logs show error about key_query, commenting line 234 in [ircd/m.cc](https://github.com/matrix-construct/construct/blob/master/ircd/m.cc) remedies the problem.

**Comment by Valinwolf** [comment] 2019-08-01 10:57
After rebuild without this patch, it seems to be working.

**Comment by Valinwolf** [comment] 2019-08-01 20:23
I think it's safe to say that this problem stems from the same issue as #95 that magically fixed itself after a clean copy of the repository was obtained.

**Comment by jevolk** [comment] 2019-08-01 20:37
> I think it's safe to say that this problem stems from the same issue as #95 that magically fixed itself after a clean copy of the repository was obtained.

Alright, so also possibly related to #84  

I'm going to close this because there's a handle on #84 and without anybody being able to reproduce or know what exactly this was it probably can't be fixed. **Please reopen** if hit again, regardless of being able to further reproduce.

Also a hint if encountering a similar issue after a large `git pull` update: Sometimes the installed `$prefix/lib/modules/construct` directory has to be cleaned and then followed by a `make install` again. Though this is required _very very_ rarely in contrast to the issue causing trouble within the repository directory.

**Comment by jevolk** [comment] 2019-08-03 21:53
Reopening after recurrence reported.

**Comment by Valinwolf** [comment] 2019-08-03 22:51
After running `git reset --hard && git clean -x -f -d` and rerunning `./autogen.sh`, I added `--enable-debug --with-assert=` to `./configure`, the error has gone away. Prior to adding these extra options, I reran everything, including resetting and cleaning the repo, at least 4 times to make sure it wasn't a fluke.

**Closed** 2022-07-22 02:19 UTC
Labels: bug
